title: Liam Pulles
author: Liam Pulles
url: "https://liampulles.com/"
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"