title: Liam Pulles
author: Liam Pulles
url: "https://liampulles.com"
email: me@liampulles.com
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title
  - scope:
      path: ""
    values:
      layout: "default"
collections:
  digital_restorations:
    output: true
    permalink: /digital_restorations/:title