title: Liam Pulles
author: Liam Pulles
url: "https://liampulles.com/"
email: me@liampulles.com
projects: https://github.com/liampulles
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"